name: Run Linters

on:
  push:
    branches: [ "feat*/*", "fix/*" ] # Run on push requests from feat/fix branches only
  pull_request:
    branches: [ "feat*/*", "fix/*" ] # Run on push requests from feat/fix branches only

jobs:
  lint:
    name: RunLinters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name: Run format check
        run: npm run format

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs
